name: Python package
on:
  push:
    branches:
      - 'main'
    paths:
      - '**.py'
      - 'pyprojec.toml'
      - 'uv.lock'
      - '.github/worflows/ci.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/worflows/ci.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Display Python version
        run: uv run python -c "import sys; print(sys.version)"
      - name: Install the project
        run: uv sync --all-extras --dev --locked
      - name: Run tests
        run: uv run pytest -vv
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: Display Python version
        run: uv run python -c "import sys; print(sys.version)"
      - name: Install the project
        run: uv sync --only-group lint
      - name: Run linter
        run: uv run ruff check src tests
      - name: Run static checker
        run: uv run mypy src tests
